[profile]
rpath = true


[unstable]
configurable-env = true
unstable-options = true

[env]
DATA_FILES_DIR = "/mnt/nfs/extra/uspto/"

[build]
rustflags = [
    "-C", "prefer-dynamic"
]


[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = [
    "-Clink-arg=-fuse-ld=lld", "-Zshare-generics=y",
    "-C", "link-arg=-Wl,-rpath,$ORIGIN"
]

