[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-Wl,-rpath,/home/henry/search/cmake-build-debug/",
    "-C", "link-args=-Wl,-rpath,/home/henry/search/cmake-build-release/"]

[unstable]
configurable-env = true
unstable-options = true

[env]
DATA_FILES_DIR = "/mnt/nfs/extra/data-files/"