[package]
name = "rust"
version = "0.1.0"
edition = "2018"
build = "src/build.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
regex = "1"
rmp-serde = "0.15.4"

[profile.dev]
rpath = true

[lib]
crate-type = ["cdylib"]