[package]
name = "rust"
version = "0.1.0"
edition = "2018"
build = "src/build.rs"

[dependencies]
fancy-regex = "0.5"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

[profile.dev]
rpath = true