[workspace]
members = ["namesdb", "webserver", "metastore", "metastore-server", "thread-check"]
default-members=["namesdb", "webserver", "metastore", "metastore-server", "thread-check"]

[profile.dev]
rpath=true


[profile.release]
rpath=true

