[workspace]
members = ["namesdb", "webserver", "metastore", "metastore-server"]
default-members=["namesdb", "webserver", "metastore", "metastore-server"]

[profile.dev]
rpath=true


[profile.release]
rpath=true

